import type { NextPage } from "next";
import React from "react";
import { useState, useEffect } from "react"
import styles from '../styles/Home.module.css'
import { ControleEditora } from "@/classes/controle/ControleEditora";
import { Livro } from "@/classes/modelo/Livro";
import { useRouter } from "next/router";
import Head from "next/head";
import { Menu } from "@/componentes/Menu";

const controleEditora = new ControleEditora();
const opcoes = controleEditora.getEditoras;
const baseURL: string = "http://localhost:3000/api/livros";


/*-----------------EM CONSTRUÇÃO----------------------*/

const incluirLivro = async (livro: Livro) => {
    const dados = await fetch(baseURL, {
        method: "POST",
        //body: JSON.stringify({ codigo_livro: codigo }),
      });
    
};

/*-----------------EM CONSTRUÇÃO----------------------*/

const LivroDados: NextPage = () => {
    const router = useRouter();

    const [titulo, setTitulo] = useState<string>("");
    const [resumo, setResumo] = useState<string>("");
    const [autores, setAutores] = useState<string>("");
    const [codEditora, setcodEditora] = useState<number>(0)

    function tratarCombo(evento: React.ChangeEvent<HTMLSelectElement>){
        setcodEditora(parseInt(evento.target.value));
    };
    
    function incluir(evento: React.FormEvent<HTMLFormElement>) {
        evento.preventDefault();
        const livro = {
            codigo: 0,
            codEditora,
            titulo,
            resumo,
            autores: autores.split("\n")
        };
        incluirLivro(livro);
        router.push("./LivroLista");
    }
    
    return (
        <div className={styles.container}>
            <Head>
                <title>Dados do Livro</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Menu/>
        <main>
            <div>
                <h1>Dados do Livro</h1>
            </div>
            <form onSubmit={(event) => incluir(event)}>
                <div className="form-group">
                    <label htmlFor="exampleInputEmail1">Titulo</label>
                    <input className="form-control mb-2" id="titulo" type="text" value={titulo} onChange={(event) => setTitulo(event.target.value)}></input>
                </div>
                <div className="form-group">
                    <label htmlFor="exampleInputEmail1">Resumo</label>
                    <textarea className="form-control mb-2" id="resumo" value={resumo} onChange={(event) => setResumo(event.target.value)} rows={3}></textarea>
                </div>
                <div className="form-group">
                    <label htmlFor="exampleFormControlSelect1">Editora</label>
                    <select className="form-control mb-4" id="editora" value={codEditora} onChange={(event) => {tratarCombo(event);}}>{
                        controleEditora.getEditoras().map((editora) => {
                            return (
                                <option value={Number(editora.codEditora)}>{editora.nome}</option>);
                        })}
                    </select>
                </div>
                <div className="form-group">
                    <label htmlFor="exampleInputEmail1">Autores (1 por linha)</label>
                    <textarea className="form-control mb-2" id="autores" value={autores} onChange={(event) => setAutores(event.target.value)} rows={3}></textarea>
                </div>
                <div>
                    <button type="submit" className="btn btn-primary mb-2">Salvar Dados</button>
                </div>
            </form>
        </main>
        </div>
    );
}

export default LivroDados;